# Generated by Django 4.2.2 on 2023-06-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='telephone number'),
        ),
    ]
